name: sqlite_entities

description:
  Defines sqlite entities.

version: 0.0.1

homepage: https://github.com/simphotonics/sqlite_entities

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: ^0.39.14 # lastest version broken!
  meta: ^1.2.2
  generic_enum: ^0.3.5
  exception_templates: ^0.0.6

dev_dependencies:
  ansicolor: ^1.0.2
  build_runner: ^1.10.1
  generic_enum_builder: ^0.3.5
  pedantic: ^1.9.2
